name: Build

on:
  push:
  pull_request:
    types: [ opened, edited ]

jobs:
  build-dotnet-framework:
    runs-on: windows-latest
    name: .NET Framework 4.7.2
    steps:

      - uses: actions/checkout@v2

      - name: Set up NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: |
          nuget restore VRCFaceTracking.sln

      - name: Build solution
        run: |
          $MS_BUILD_PATH = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $MS_BUILD_PATH + ';' + $env:PATH

          foreach ($config in 'Debug', 'Release') {
            Write-Host "Building $config";
            msbuild -v:m -m -restore -t:Build -p:Configuration=$config -p:TargetFramework=net472 VRCFaceTracking/VRCFaceTracking.csproj
          }

      - name: Capture version
        id: versioning
        run: |
          echo "::set-output name=VERSION::$(Get-Date -Format "yyyy.MM.dd").$(git rev-parse --short HEAD)"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: VRCFaceTracking_dev_${{ steps.versioning.outputs.VERSION }}
          path: VRCFaceTracking/bin/*
